WebApplication2/WebApplication2/Controllers/ProcessModelController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class ProcessModelController : Controller
    {
        ProcessModel PModel = new ProcessModel();
        public ActionResult Questions(Account User)
        {
            ViewData["id"] = User.AccountId;
            ViewData["questions"] = PModel.Questions;
            ViewData["multAnswers"] = PModel.MultipleChoiceAnswers;
            ViewData["isValid"] = "true";
            ViewData["answers"] = ViewData["answers"] = new string[92] { "0True", "1True", "2True", "3True", "4True", "5False", "test", "7False", "8False", "9very little", "10False", "11False", "12at the end", "13very little to no time", "14False", "15False", "16Fast", "17False", "18Less than a Year", "19False", "20Every 1-3 weeks", "21Every 1-3 weeks", "22False", "23False", "24False", "25very", "26True", "27very", "28False", "29False", "30little", "31little", "32average amount", "33love it", "34False", "35spread out across country", "36low - Medium", "37High", "38False", "39False", "40True", "41False", "42False", "43low", "44True", "45One", "46False", "47True", "48True", "49True", "50None", "51True", "52True", "53False", "54Medium", "55True", "56True", "57False", "58False", "59False", "60Updated Often", "61False", "62False", "63False", "64Low Budget", "65Low Budget", "66Low Budget", "67Low Budget", "68False", "69False", "70False", "71Small", "72True", "73False", "74Flexable", "75True", "76True", "77True", "78True", "79True", "80True", "81True", "82True", "83True", "84False", "85False", "86False", "87False", "88True", "89False", "90False", "91False" };

            return View("Questions",User);
        }
        [HttpPost]
        public ActionResult Test(FormCollection form)
        {
            string[] info = new string[form.Count];
            form.CopyTo(info, 0);
            int id = Convert.ToInt16(info[0]);
            string model = info[1];

           //RegistrationEntities1Entities1 db = new RegistrationEntities1Entities1();
			RegistrationEntities1 db = new RegistrationEntities1();

            db.ProjectTables.Add(new ProjectTable
            {
                ProcessModelChosen = model
            });

            db.SaveChanges();

            List<ProjectTable> projectTables = db.ProjectTables.ToList();
            ProjectTable justAdded = projectTables.Last();

            db.JunctionTableProjectAndAccountV2.Add(new JunctionTableProjectAndAccountV2
            {
                AID = id,
                PId = justAdded.ProjectId,
                Responsibilities = "Leader",
                Role = "Leader"
            });

            db.SaveChanges();

            leaderTableV2 leader = db.leaderTableV2.Find(id);
            Account User = new Account();
            User.AccountId = leader.Id;
            User.Rank = "Leader";
            User.UserName = leader.UserName;

            return RedirectToAction("ExistingProjects", "Project", User);
        }
        //for training
        public ActionResult TrainingData()
        {
            ViewData["questions"] = PModel.Questions;
            ViewData["multAnswers"] = PModel.MultipleChoiceAnswers;
            ViewData["isValid"] = "true";
            ViewData["answers"] =new string[1]{"test"};
            ViewData["answers"] = new string[92]{"0True", "1True", "2True", "3True", "4True", "5False", "test", "7False", "8False", "9very little", "10False", "11False", "12at the end", "13very little to no time", "14False", "15False", "16Fast", "17False", "18Less than a Year", "19False", "20Every 1-3 weeks", "21Every 1-3 weeks", "22False", "23False", "24False", "25very", "26True", "27very", "28False", "29False", "30little", "31little", "32average amount", "33love it", "34False", "35spread out across country", "36low - Medium", "37High", "38False", "39False", "40True", "41False", "42False", "43low", "44True", "45One", "46False", "47True", "48True", "49True", "50None", "51True", "52True", "53False", "54Medium", "55True", "56True", "57False", "58False", "59False", "60Updated Often", "61False", "62False", "63False", "64Low Budget", "65Low Budget", "66Low Budget", "67Low Budget", "68False", "69False", "70False", "71Small", "72True", "73False", "74Flexable", "75True", "76True", "77True", "78True", "79True", "80True", "81True", "82True", "83True", "84False", "85False", "86False", "87False", "88True", "89False", "90False", "91False"};
            ViewData["result"] = "";
            return View();
        }
        //for training
        public ActionResult TrainData(FormCollection form)
        {
            string[] Answers2= new string[92] { "0True", "1True", "2True", "3True", "4True", "5False", "test", "7False", "8False", "9very little", "10False", "11False", "12at the end", "13very little to no time", "14False", "15False", "16Fast", "17False", "18Less than a Year", "19False", "20Every 1-3 weeks", "21Every 1-3 weeks", "22False", "23False", "24False", "25very", "26True", "27very", "28False", "29False", "30little", "31little", "32average amount", "33love it", "34False", "35spread out across country", "36low - Medium", "37High", "38False", "39False", "40True", "41False", "42False", "43low", "44True", "45One", "46False", "47True", "48True", "49True", "50None", "51True", "52True", "53False", "54Medium", "55True", "56True", "57False", "58False", "59False", "60Updated Often", "61False", "62False", "63False", "64Low Budget", "65Low Budget", "66Low Budget", "67Low Budget", "68False", "69False", "70False", "71Small", "72True", "73False", "74Flexable", "75True", "76True", "77True", "78True", "79True", "80True", "81True", "82True", "83True", "84False", "85False", "86False", "87False", "88True", "89False", "90False", "91False" };
            Debug.Print("Answers2: " +Answers2.Length.ToString());
            Debug.Print("Train COUNT IN CONTROLLER");
            string[] Answers = new string[form.Count]; //for now hard code it
            Debug.Print("Form length is: " + form.Count.ToString());
            form.CopyTo(Answers, 0);
            for(int i=0; i<Answers.Length; i++)
            {
                Debug.Write(Answers[i]+", ");
            }
            Debug.Print("Length of form is: ");
            Debug.Print(Answers.Length.ToString());
            if (Answers.Length==93) //if all the questions were answered
            {
                string winner = form[form.Count - 1];
                //Debug.Print("winner: " + winner);
                string key= form.GetKey(form.Count-1);
                form.Remove(form.GetKey(form.Count - 1));//hopefully removing the winner from the form 
                Answers = new string[form.Count];
                form.CopyTo(Answers, 0);
                string[] OldAnswers = new string[form.Count];
                Answers.CopyTo(OldAnswers, 0);
                PModel.Answers = PModel.RemoveQuestionIDS(Answers);
                /*Debug.Print("Answers Again: ");
                for (int i = 0; i < Answers.Length; i++) //test
                {
                    Debug.Write(Answers[i] + ",");
                }*/
                int score =PModel.TrainData(winner);
     
                ViewData["isValid"] = "true";
                ViewData["answers"] = OldAnswers;
                ViewData["questions"] = PModel.Questions;
                ViewData["multAnswers"] = PModel.MultipleChoiceAnswers;
                ViewData["result"] = winner + " has been added to the database with a score of " + score.ToString();
                return View("TrainingData");
            }
            else
            {
                ViewData["questions"] = PModel.Questions;
                ViewData["multAnswers"] = PModel.MultipleChoiceAnswers;
                ViewData["isValid"] = "false";
                ViewData["answers"] = Answers;
                ViewData["result"] = "";
                return View("TrainingData");
            }

        }
        [HttpPost]
        public ActionResult Result(FormCollection form, Account User) 
        {
          
            Debug.Print("ANS COUNT IN CONTROLLER");

            //BRad Removed this
            //string[] Answers = new string[form.Count]; //for now hard code it
            //form.CopyTo(Answers, 0);
            //End Brads Remove

            /*Debug.Print("Length of form is: ");
            Debug.Print(Answers.Length.ToString());
            for (int i = 0; i < Answers.Length; i++)
            {
               Debug.Write(Answers[i] +",");
            }*/

            /**** Brads Code
            Adding the Account Id makes the form length 1 more larger, I had to fix it
            */
            string[] Answers = new string[form.Count - 1];
            string[] wrongAnswers = new string[form.Count];
            form.CopyTo(wrongAnswers, 0);
            for (int i = 0; i < wrongAnswers.Length - 1; i++)
            {
                Answers[i] = wrongAnswers[i + 1];
            }
            // BRads code ends

            if (PModel.IsValid(Answers))
            {
                Answers = PModel.RemoveQuestionIDS(Answers);
                PModel.Answers = Answers;
                PModel.EliminateProcessModels();
                string Result=PModel.ChooseProcessModels();
                ViewData["result"] = Result;
                return View("Result",User);
            }
            else
            {
                ViewData["questions"] = PModel.Questions;
                ViewData["multAnswers"] = PModel.MultipleChoiceAnswers;
                ViewData["isValid"] = "false";
                ViewData["answers"] = Answers;
                return View("Questions", User);
            }
          }
        
    }
}

WebApplication2/WebApplication2/Views/ProcessModel/Questions.cshtml
@model WebApplication2.Models.Account

<head>
    <title>@{ViewBag.Title = "Questions"; }</title>
    <link rel="stylesheet" type="text/css" href="~/Content/PMStyle.css">
    <script src="~/Scripts/TabbedMenu.js"></script> 
</head>
<!DOCTYPE html>
<html>
<body>
    <h1>Process Model Survey</h1><hr />
    <div align="left" id="q_form">
    @using (Html.BeginForm("Result", "ProcessModel"))
    {
        bool IsCheckedTrue = false;
        bool IsCheckedFalse = false;
        bool IsCheckedMult = false;
        if (ViewData["isValid"].Equals("false"))
        { 
            <br />@Html.Label("Did Not answer all of the questions", new { @class = "warning" });<br />
        }
        @Html.HiddenFor(Model => Model.AccountId)
        string[,] Questions = (string[,])ViewData["questions"];
        string[,] MultAnswers = (string[,])ViewData["multAnswers"];
        string[] Answers = (string[])ViewData["answers"];
        System.Collections.ArrayList Categories = new System.Collections.ArrayList();

        for (int i = 0; i < Questions.GetLength(0); i++)
        { 
           
            if (!Categories.Contains(Questions[i, 1].ToString().Trim()))
            {
                 
                <br /><div id=@Questions[i, 1].ToString().Trim() class="question_cat_header">
                    <h2> @Questions[i, 1].ToString().Trim() </h2>
                </div>
                <hr/>
                Categories.Add(Questions[i, 1].ToString().Trim());
            }
            if (Questions[i, 2].ToString().Trim().Equals("True or False"))
            {
                @:<div class="question_row">
                    <div class="question">
                        @Html.Label(Questions[i, 0].ToString().Trim())
                    </div>
                if (Answers[0] != "test" && Array.Exists(Answers, element => element == i.ToString() + "True")) { IsCheckedTrue = true; }
                else if (Answers[0] != "test" && Array.Exists(Answers, element => element == i.ToString() + "False")) { IsCheckedFalse = true; }
                /*<div class="answers">
                    
                    <table>
                        <tr>
                            <th>@Html.Label("True", new { @class = "label" })</th>
                            <th>@Html.Label("False", new { @class = "label" })</th>
                        </tr>
                        <tr>
                            <td>@Html.RadioButton("answer[" + i + "]", i + "True", IsCheckedTrue, new { @class = "rbutton" })</td>
                            <td>@Html.RadioButton("answer[" + i + "]", i + "False", IsCheckedFalse, new { @class = "rbutton" })</td>
                        </tr>
                    </table>
                </div>*/
                <div class="answers">
                    <div class="col-sm-3">
                    <div class="checkbox_group">
                        @Html.Label("True", new { @class = "label" })
                        @Html.RadioButton("answer[" + i + "]", i + "True", IsCheckedTrue, new { @class = "rbutton radio" })
                    </div></div>
                    <div class="checkbox_group col-sm-4">
                        @Html.Label("False", new { @class = "label" })
                        @Html.RadioButton("answer[" + i + "]", i + "False", IsCheckedFalse, new { @class = "rbutton radio" })
                    </div>
                </div>
                IsCheckedTrue = false;
                IsCheckedFalse = false;
        <br/><br>
        @:</div>
            }
            else if (Questions[i, 2].ToString().Trim().Equals("Short Answer"))
            {
                @:<div class="question_row">
                    <div class="question">
                        @Html.Label(Questions[i, 0].ToString().Trim())
                    </div>
                    <div class="answers">
                        @Html.Label("Short Answer", new { @class = "label" });<br/>
                        @Html.TextArea("answer[" + i + "]");
                    </div><br />
                 @:</div>
            }
            else //multiple choice
            {
                @:<div class="question_row">
                <div class="question">
                    @Html.Label(Questions[i, 0].ToString().Trim())
                </div>
                int QuestionID = i + 1;
                for (int j = 0; j < MultAnswers.GetLength(0); j++)
                {
                    if (QuestionID == Convert.ToInt32(MultAnswers[j, 0])) //the question ids are the same
                    {
                        @:<div class="answers">
                        int m = 1;
                        while (!MultAnswers[j, m].Trim().Equals("Empty") && m < 5)
                        {
                            if (Answers[0] != "test" && Array.Exists(Answers, element => element == i + MultAnswers[j, m].Trim()))
                            {
                                IsCheckedMult = true;
                            }
                            <div class="col-sm-3">
                                <div class="checkbox_group">
                               
                                    @Html.Label(MultAnswers[j, m].Trim(), new { @class = "label" });
                                  
                                    @Html.RadioButton("answer[" + i + "]", i + MultAnswers[j, m].Trim(), IsCheckedMult, new {@class="radio"});
                                </div>
                            </div>
                            m++;
                            IsCheckedMult = false;
                        }//end while
                        @:</div>

                         /*@:<table>
                         for (int n = 0; n < 2; n++)
                         {
                             @:
                        <tr>
                             int m = 1;
                             while (!MultAnswers[j, m].Trim().Equals("Empty") && m < 5)
                             {
                                 if (Answers[0] != "test" && Array.Exists(Answers, element => element == i + MultAnswers[j, m].Trim()))
                                 {
                                     IsCheckedMult = true;
                                 }
                                 if (n == 0){
                                <th>@Html.Label(MultAnswers[j, m].Trim(), new {@class="label" });</th>}
                                 else{
                                <td>@Html.RadioButton("answer[" + i + "]", i + MultAnswers[j, m].Trim(), IsCheckedMult);</td>}
                                 m++;
                                 IsCheckedMult = false;
                             }//end while
                         @:
    </tr>
                         }//end for (loop twice)
                         @:
    </table>*/
                      
                    }//end if
                }//end for
                @:</div>
            }//end else
        }//end question for loop
        <hr />
        <div id="submit_form" align="center">
            <input type="submit" value="Submit" onclick="return confirm('Are you sure you want to submit this form');"><br /><br />
        </div>
}
</div>







    </body>
</html>

WebApplication2/WebApplication2/Views/ProcessModel/Result.cshtml
@model WebApplication2.Models.Account

<head>
    <title>@{ViewBag.Title = "Result"; }</title>
    <link rel="stylesheet" type="text/css" href="~/Content/PMResultStyle.css">
    <script src="~/Scripts/ProjectManager.js"></script>
 
</head>

<h2>Results</h2><hr/>
@using (Html.BeginForm("Test", "ProcessModel", FormMethod.Post))
{
    @Html.HiddenFor(Model => Model.AccountId)
    @Html.Hidden(ViewData["result"].ToString(), ViewData["result"].ToString())
    string ImageURL;
    if (ViewData["result"].ToString() == "Waterfall") { ImageURL = "~/Content/Images/waterfall.jpg"; }
    else if(ViewData["result"].ToString() == "Iterative Waterfall") { ImageURL = "~/Content/Images/iterative_waterfall.jpg"; }
    else if (ViewData["result"].ToString() == "COTS") { ImageURL = "~/Content/Images/COTS.jpg"; }
    else { ImageURL = "~/Content/Images/RAD.jpg"; }
    <div align="center">
        <div>
            @Html.Label(ViewData["result"].ToString(), ViewData["result"].ToString(), new {@id="pmodel"})
        </div>
        <div>
            <img class="model_pic" src=@Url.Content(ImageURL) alt="some_text">
        </div>
        <br />
        <div align="center">
            <input type="submit" value="Keep Suggestion" class="button btn-primary">
        </div>
    </div>
}
<div>
    @{
        List<SelectListItem> dropDown = new List<SelectListItem>();
        dropDown.Add(new SelectListItem { Value = "Waterfall", Text = "Waterfall" });
        dropDown.Add(new SelectListItem { Value = "Iterative Waterfall", Text = "Iterative Waterfall" });
        dropDown.Add(new SelectListItem { Value = "RAD", Text = "RAD" });
        dropDown.Add(new SelectListItem { Value = "COTS", Text = "COTS" });
    }
</div>
<div align="right">
    @using (Html.BeginForm("Test", "ProcessModel"))
    {
        <br />
        @Html.HiddenFor(Model => Model.AccountId)
            <br />
            @Html.DropDownList("DropChoice", new SelectList(dropDown, "Value", "Text"))
            <input type="submit" value="Override Suggestion" class="button btn-primary">
    }
</div>

WebApplication2/WebApplication2/Views/ProcessModel/Test.cshtml

@{
    ViewBag.Title = "Test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Test</h2>


WebApplication2/WebApplication2/Views/ProcessModel/TrainingData.cshtml

@{
    ViewBag.Title = "TrainingData";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>TrainingData</h2>

@{
    ViewBag.Title = "Questions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <!--<style>
<a href="~/Views/ProcessModel/Test.cshtml">~/Views/ProcessModel/Test.cshtml</a>
        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
        }
        li {
            display: inline;
        }
    </style>-->
</head>
<body>

    <ul>
        <li><a href="#Requirements">Requirements</a></li>
        <li><a href="#Customers">Customers</a></li>
        <li><a href="#Team">Team</a></li>
        <li><a href="#Software">Software</a></li>
        <li><a href="#Management">Management</a></li>
        <li><a href="#Money">Money</a></li>
        <li><a href="#Size">Size</a></li>
        <li><a href="#Risk">Risk</a></li>
        <li><a href="#Planning">Planning</a></li>
        <li><a href="#Process">Process</a></li>
    </ul>
    <h1>Process Model Survey</h1>



    @using (Html.BeginForm("TrainData", "ProcessModel"))
    {
        bool IsCheckedTrue = false;
        bool IsCheckedFalse = false;
        bool IsCheckedMult = false;
        @Html.Label((string)ViewData["result"]);
        if (ViewData["isValid"].Equals("false"))
        {   <br />
        @Html.Label("Did Not answer all of the fields");
            <br />
        }
        string[,] Questions = (string[,])ViewData["questions"];
        string[,] MultAnswers = (string[,])ViewData["multAnswers"];
        string[] Answers = (string[])ViewData["answers"];
        System.Collections.ArrayList Categories = new System.Collections.ArrayList();

        for (int i = 0; i < Questions.GetLength(0); i++)
        {

            if (!Categories.Contains(Questions[i, 1].ToString().Trim()))
            {
                <br />
                <div id=@Questions[i, 1].ToString().Trim()></div>
                <h2> @Questions[i, 1].ToString().Trim() </h2>
                Categories.Add(Questions[i, 1].ToString().Trim());
                <br />
            }
            @Html.Label(Questions[i, 0].ToString().Trim());
            if (Questions[i, 2].ToString().Trim().Equals("True or False"))
            {
                if (Answers[0] != "test" && Array.Exists(Answers, element => element == i.ToString() + "True"))
                {
                    IsCheckedTrue = true;
                }
                else if (Answers[0] != "test" && Array.Exists(Answers, element => element == i.ToString() + "False"))
                {
                    IsCheckedFalse = true;
                }
                <br>

                @Html.Label("True");
                @Html.RadioButton("answer[" + i + "]", i + "True", IsCheckedTrue);
                @Html.Label("False");
                @Html.RadioButton("answer[" + i + "]", i + "False", IsCheckedFalse);
                IsCheckedTrue = false;
                IsCheckedFalse = false;
                <br>
            }
            else if (Questions[i, 2].ToString().Trim().Equals("Short Answer"))
            {
                <br>
                @Html.Label("Short Answer");
                @Html.TextArea("answer[" + i + "]");
                <br>
            }
            else //multiple choice
            {
                <br />
                int QuestionID = i + 1;
                for (int j = 0; j < MultAnswers.GetLength(0); j++)
                {
                    if (QuestionID == Convert.ToInt32(MultAnswers[j, 0])) //the question ids are the same
                    {
                        int m = 1;
                        while (!MultAnswers[j, m].Trim().Equals("Empty") && m < 5)
                        {
                            if (Answers[0] != "test" && Array.Exists(Answers, element => element == i + MultAnswers[j, m].Trim()))
                            {
                                IsCheckedMult = true;
                            }
                            @Html.Label(MultAnswers[j, m].Trim());
                            @Html.RadioButton("answer[" + i + "]", i + MultAnswers[j, m].Trim(), IsCheckedMult);
                            m++;
                            IsCheckedMult = false;
                        }

                      
                    }
                }
                <br />
            }
        }
        <h2> Desired Process Model: </h2>
        <br />
        @Html.Label("Waterfall");
        @Html.RadioButton("pMod", "WaterfallTable2");
        @Html.Label("Iterative Waterfall");
        @Html.RadioButton("pMod", "WaterfallIterationTable");
        @Html.Label("RAD");
        @Html.RadioButton("pMod", "RADTable");
        @Html.Label("COTS");
        @Html.RadioButton("pMod", "COTSTable");
    
        <input type="submit" value="Submit">
    }
</body>
</html>